# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.hostname = "ControllerSynthesis-DEMO-VM"

  config.vm.provider "virtualbox" do |vb|
      # Enable GUI, configure RAM and disable USB
      vb.gui = true
      vb.memory = "1024"
	  vb.name = "ControllerSynthesis-DEMO-VM"
	  vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	  vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end

  # Run provisioning script
  config.vm.provision :shell, privileged: false, path: "setup.sh"

  # Reload VM after provisioning, requires vagrant-reload plugin  
  config.vm.provision :reload

end